### ISSUE TITLE
Cadastro de áreas de interesse e sugestão de cadeiras optativas nestas áreas

### ISSUE THREAD

**Issue by ghost** [luciannojunior/gradccc-app#12]
Eu, como estudante usuário, desejo cadastrar minhas áreas interesse dentro do âmbito da ciência da computação e receber do aplicativo sugestões das cadeiras relacionadas a essas áreas.

**Comment by ThaynanAndrey** [comment]
Foi invalidado pelo cliente em reunião descrita na ATA III.
